### ISSUE TITLE
EO term request: paper growth medium?

### ISSUE THREAD

**Issue by elsadebecker** [Planteome/plant-environment-ontology#102]
I'd like an EO growth medium term for 'grown in a paper towel' as in [Genetic architecture of cold tolerance in rice (Oryza sativa) determined through high resolution genome-wide analysis](http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0172133).

**Comment by cooperl09** [comment]
Created new term: 
paper towel growth medium (EO:0001063): "An in vitro solid growth medium (EO:0007262) composed of paper towels.
Exact synonym: ragdoll method

**Comment by elsadebecker** [comment]
Thanks!
